language: node_js

services:
  - docker

node_js:
  - '12'
  - '10'
  - '8'
  - node

cache: npm

install:
  - npm ci

script:
  - npm run test:lint
  - npm run build
  - npm link
  - mkdir -p testing
  - npm run test:func -- --runInBand --testTimeout=10000

jobs:
  include:
    - stage: npm beta release
      if: branch = master AND type != pull_request
      node_js: '10'
      script:
        - npm run build
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
        - npm publish --tag beta

    - stage: npm release
      if: tag IS present
      script: npm run build
      node_js: '10'
      script:
        - npm run build
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
        - node ./scripts/release.js