language: node_js
node_js:
  - '12'
  - '10'
  - '8'

cache: npm
install:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run build
jobs:
  include:
    - stage: npm beta release
      if: branch = edge
      node_js: '10'
      script: npm run build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        tag: beta
        on:
          branch: edge
    - stage: npm release
      if: branch = master
      script: npm run build
      node_js: '10'
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          branch: master
          tags: true